<?php

/**
 * Implements hook_field_formatter_info().
 */
function userprofile_field_formatter_info() {
  return array(
    'list_show_all' => array(
      'label' => t('List with unchecked'),
      'field types' => array('list_integer', 'list_float', 'list_text', 'list_boolean'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function userprofile_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  $outputs = '';

  switch ($display['type']) {
    case 'list_show_all':
      $allowed_values = list_allowed_values($field, $instance, $entity_type, $entity);
      foreach ($allowed_values as $key => $allowed_value) {
        $checked = FALSE;
        foreach ($items as $item) {
          if ($item['value'] == $key) {
            $checked = TRUE;
          }
        }
        $output = '<li class="list-item-icon">'
          . '<span class="list-item-' . ($checked ? 'checked' : 'unchecked') . '"
            title="' . ($checked ? 'Документ получен' : 'Документ не получен') . '"></span>'
          . field_filter_xss($allowed_values[$key])
          . '</li>';
        $outputs .= $output;
      }
      $element[0] = array('#markup' => $outputs);
      break;
  }

  return $element;
}

function userprofile_field_attach_view_alter(&$output, $context) {
  if (isset($context['display']['type']) && $context['display']['type'] == 'list_show_all' ) {
    $fieldnames = array_keys($output);
    $fieldname = reset($fieldnames);
    if (isset($result[$fieldname])) {
      if (empty($result[$fieldname]['#items'])) {
        $result[$fieldname]['#items'][0] = TRUE;
      }
    }
  }
  elseif ($context['entity_type'] == 'profile2' && $context['entity']->type == 'scans') {
    $entity_type = $context['entity_type'];
    $entity = $context['entity'];
    $view_mode = $context['view_mode'];

    list($id, $vid, $bundle) = entity_extract_ids($entity_type, $entity);
    foreach (field_info_instances($entity_type, $bundle) as $field_name => $instance) {
      if (!empty($output[$field_name])) {
        continue;
      }
      $display = field_get_display($instance, $view_mode, $entity);
      $field = field_info_field($field_name);
      if ($field['type'] == 'image') {
        $markup = 'Скан-копии еще не загружены!';
        if (empty($context['language'])) {
          $language = field_language($entity_type, $entity, $field_name);
        }
        else {
          $language = $context['language'];
        }

        $output[$field_name] = array(
          '#theme' => 'field',
          '#title' => $instance['label'],
          '#label_display' => 'hidden',
          '#weight' => $display['weight'],
          '#field_type' => $field['type'],
          '#field_name' => $field_name,
          '#bundle' => $bundle,
          '#object' => $entity,
          '#entity_type' => $entity_type,
          '#view_mode' => $view_mode,
          '#language' => $language,
          '#formatter' => $display['type'],
          '#items' => array(
            0 => array('value' => $markup),
          ),
          0 => array(
            '#markup' => $markup,
          ),
        );
      }
    }
  }
}