<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'field.profile2.field_add_documents.documents' => '3b41ad069a58d9ac966a74c091ba46f392012b07',
  'field.profile2.field_insurance.scans' => 'c9aeea5c7fb9fd77ec3539c76e2a7ae1766ee550',
  'field.profile2.field_payment_reciept.scans' => 'ae0c37140028c99b568c3e40da801b04a94f34c7',
  'field.profile2.field_post_despatch.scans' => 'a5dbe3077d1295d7fc788d1fae902b3c1aa2202d',
  'field.profile2.field_required_documents.documents' => '8ced2ab5de011b0f6393077e11722b34a06cf125',
  'profile2_type.documents' => '3f729ffe227918e3b71d6d4b3463cfb74399e7f2',
  'profile2_type.scans' => '8512220a7135bac73b2f6efe0dfe49ab590eed7e',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'field_sql_storage',
  'list',
  'options',
  'image',
  'entity',
  'profile2',
);
